/*
 * Copyright (C) 2021-2026, Dylan Liu
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even an implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 */

/**
 * @file maintain.cpp
 * @brief Implementation of maintenance operation for DHTDynamic strategy
 * @details Handles three maintenance operations on the dynamic PDP state:
 *
 *          **Design Principle:**
 *          maintenance() is responsible ONLY for StateStore updates.
 *          Tag management is the caller's responsibility:
 *          - New tags are generated by the caller (Admin) via generateTags()
 *          - New tags are sent to Storage for persistence
 *          - maintenance() does NOT touch the Tags collection at all
 *
 *          This separation exists because:
 *          1. Tags and StateStore are independent data paths
 *             (Tags → Storage, StateStore → TPA)
 *          2. The TPA running maintenance does not hold the private key
 *             needed for tag generation
 *          3. Tag persistence is Storage's responsibility, not the
 *             audit strategy's
 *
 *          Operations:
 *
 *          1. Update: Block content changed.
 *             - Caller (Admin) generates new tags via generateTags()
 *               and sends them to Storage
 *             - maintenance() bumps version and refreshes timestamp
 *               in StateStore via modifyBlock()
 *
 *          2. Insert: New block added at a specific index.
 *             - Caller (Admin) generates new tags via generateTags()
 *               and sends them to Storage
 *             - maintenance() inserts BlockMetadata into StateStore
 *               via insertBlock()
 *
 *          3. Delete: Block removed from the file.
 *             - Caller (Admin) removes tags from Storage
 *             - maintenance() deletes BlockMetadata from StateStore
 *               via deleteBlock()
 *
 * @author Dylan Liu
 * @version 2.0.0
 * @date 2026-07-12
 * @copyright Copyright (C) 2021 - 2026, Dylan Liu
 */

#include "DHTDynamicAuditStrategy/strategy.h"
#include "DHTDynamicAuditStrategy/maintain_types.h"
#include "DHTDynamicAuditStrategy/state_stores/versioned_block_metadata.h"
#include "ChordAuditMatrixLib/implementations/audit/state_stores/dynamic_pdp_state_store.h"
#include "DHTDynamicAuditStrategy/common.h"
#include "ChordAuditMatrixLib/interfaces/audit/dynamic_strategy.h"

#include <chrono>
#include <memory>
#include <stdexcept>

#include <spdlog/spdlog.h>

namespace CAMatrix::Audit::Strategies {

using namespace DHTDynamic;

CAMatrix::Audit::Messages::MaintainResult
DHTDynamicAuditStrategy::maintenance(
    const CAMatrix::Audit::Messages::MaintainRequest& input)
{
    using namespace CAMatrix::Audit::Messages;

    // ── Validate request ──
    if (!input.ext) {
        throw std::runtime_error("DHTDynamic maintenance: ext is required");
    }

    auto ext = std::dynamic_pointer_cast<DHTDynamicMaintainExt>(input.ext);
    if (!ext) {
        throw std::runtime_error("DHTDynamic maintenance: ext must be DHTDynamicMaintainExt");
    }

    if (ext->fileId.empty()) {
        throw std::runtime_error("DHTDynamic maintenance: fileId is required");
    }

    // ── Validate stateStore injection ──
    if (!stateStore_) {
        throw std::runtime_error("DHTDynamic maintenance: stateStore not injected");
    }

    if (!stateStore_->hasFile(ext->fileId)) {
        throw std::runtime_error("DHTDynamic maintenance: file '" + ext->fileId + "' not found in stateStore");
    }

    // ── Current timestamp for BlockMetadata updates ──
    const auto now = static_cast<std::uint64_t>(
        std::chrono::duration_cast<std::chrono::seconds>(
            std::chrono::system_clock::now().time_since_epoch())
            .count());

    // ── Dispatch by operation type ──
    switch (ext->opType) {
        case MaintenanceOpType::Update:
            return handleUpdate(ext, now);

        case MaintenanceOpType::Insert:
            return handleInsert(ext, now);

        case MaintenanceOpType::Delete:
            return handleDelete(ext);

        default:
            throw std::runtime_error("DHTDynamic maintenance: unsupported operation type " +
                std::to_string(static_cast<std::uint8_t>(ext->opType)));
    }
}

// ── Update: bump version, refresh timestamp in StateStore ──

CAMatrix::Audit::Messages::MaintainResult
DHTDynamicAuditStrategy::handleUpdate(
    std::shared_ptr<DHTDynamic::DHTDynamicMaintainExt> ext,
    std::uint64_t now)
{
    using namespace CAMatrix::Audit::Messages;

    if (ext->blockIndices.empty()) {
        throw std::runtime_error("DHTDynamic Update: blockIndices is required");
    }

    for (const auto blockIndex : ext->blockIndices) {
        // Validate block exists in stateStore
        auto existingMeta = stateStore_->getBlockMetadata(ext->fileId, blockIndex);
        auto existingDhtMeta = std::dynamic_pointer_cast<::CAMatrix::Audit::Core::VersionedBlockMetadata>(existingMeta);
        if (!existingDhtMeta) {
            throw std::runtime_error(
                "DHTDynamic Update: block " + std::to_string(blockIndex) +
                " metadata is not VersionedBlockMetadata or does not exist");
        }

        // Bump metadata: modifyBlock reads current metadata, calls bump()
        // which increments version and refreshes timestamp.
        stateStore_->modifyBlock(ext->fileId, blockIndex);

        spdlog::debug("DHTDynamic Update: block {} version bumped for file '{}'",
                       blockIndex, ext->fileId);
    }

    MaintainResult result;
    return result;
}

// ── Insert: add BlockMetadata in StateStore ──

CAMatrix::Audit::Messages::MaintainResult
DHTDynamicAuditStrategy::handleInsert(
    std::shared_ptr<DHTDynamic::DHTDynamicMaintainExt> ext,
    std::uint64_t now)
{
    using namespace CAMatrix::Audit::Messages;

    if (ext->blockIndices.empty()) {
        throw std::runtime_error("DHTDynamic Insert: blockIndices is required");
    }

    for (const auto blockIndex : ext->blockIndices) {
        // Insert BlockMetadata into stateStore (internally creates default metadata via factory)
        stateStore_->insertBlock(ext->fileId, blockIndex);

        spdlog::debug("DHTDynamic Insert: block {} metadata inserted for file '{}'",
                       blockIndex, ext->fileId);
    }

    MaintainResult result;
    return result;
}

// ── Delete: remove BlockMetadata from StateStore ──

CAMatrix::Audit::Messages::MaintainResult
DHTDynamicAuditStrategy::handleDelete(
    std::shared_ptr<DHTDynamic::DHTDynamicMaintainExt> ext)
{
    using namespace DHTDynamic;
    using namespace CAMatrix::Audit::Messages;

    if (ext->blockIndices.empty()) {
        throw std::runtime_error("DHTDynamic Delete: blockIndices is required");
    }

    for (const auto& blockIndex : ext->blockIndices) {
        // Delete BlockMetadata from stateStore
        stateStore_->deleteBlock(ext->fileId, blockIndex);

        spdlog::debug("DHTDynamic Delete: block {} removed from stateStore for file '{}'",
                       blockIndex, ext->fileId);
    }

    MaintainResult result;
    return result;
}

} // namespace CAMatrix::Audit::Strategies
